### PR TITLE
JPQL Refactor - narrow down query methods (Closes #100)

### LINKED ISSUE #75: 🐛 [BUG] - <Some Items in database list do not have a popup window >
### Description

Some items such as carrot, spring onions and mushroom do not open a new popup window which lets us add it to the list. 

### Reproduction URL

https://github.com/SE310-Team1/ShoppIt

### Reproduction steps

```bash
1. Go to 'SearchPopUpScene'
2. Click on 'carrots' 
3. See error
```

### Screenshots

```bash
![DESCRIPTION](LINK.png)
```

### Logs

_No response_

### OS

Windows

### LINKED ISSUE #100: 💡 [REQUEST] - <Queries not utilizing JPQL>
### Start Date

_No response_

### Implementation PR

_No response_

### Reference Issues

_No response_

### Summary

Queries for items are not utilizing JPQL to narrow down what's retrieved. Rewriting JPQL queries to be more specific will make retrieving and working with database items in code base easier. 

### Basic Example

Example: being able to retrieve items based on their attributes properly, instead of just getting all database items from the database. 

### Drawbacks

_No response_

### Unresolved questions

_No response_

### PR DESCRIPTION
**Pull request by ochu761**
Closes #100. Peer coding with @ktha423 @jzho987

- Removed unused updateImage code from previous bug fix #75 from PR #82 
- Added more specific query methods for getting table and attribute of a table.
- Made generic getFromDatabase method private to discourage using HQL queries externally.

### CODE REVIEW

**Review by poli648 — APPROVED** [review]
The code looks good, this will make it much getting what we need from the database with jpql much easier. Nice work

**Comment by mmcc944** [comment]
You mentioned that you made more specific query methods but queries still get the entire table rather than narrowing down. Is there a reason you didn't

File: ShoppIt/src/main/controllers/MainController.java [hunk 1]
```diff
@@ -30,7 +30,7 @@ public class MainController implements Initializable {
     public void initialize(URL arg0, ResourceBundle arg1) {
         DatabaseManager DB = new DatabaseManager();
 
-        lists = DB.getFromDatabase(ShoppingList.class, "FROM ShoppingList s");
+        lists = DB.getTable(ShoppingList.class, "ShoppingList");
```
Comment (ochu761) [inline ShoppIt/src/main/controllers/MainController.java:33]: @mmcc944 
> You mentioned that you made more specific query methods but queries still get the entire table rather than narrowing down. Is there a reason you didn't

Good question! We noticed that in the cases where the queries fetched the whole table, the functionality actually required access to each item in the table (such as in the above code snippet). However, we have added an additional method that only fetches the attributes of a table if needed, e.g: get FoodItem productName

"Narrowing down" in this case meant instead of needing to write the query yourself to get an attribute or field, we added more specific methods that sets up the JPQL query for you; I should have clarified this better.
